---
language: c

install:
  - sudo apt-get -y install gfortran cmake

script:
  - ./bin/fetch-configlet
  - ./bin/configlet lint .
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" ..
  - make
  - ctest -V

sudo: required

